### ISSUE TITLE
Over than 30 errors

### ISSUE THREAD

**Issue by mvorisis** [jasnig/CollectionViewLayout#1]
Hello I open it with xcode 7.3.1 and i can't test it because it returns over than 30 errors.
Is this made with swift 3 and this is why I'm getting all these errors?
thank you

**Comment by jasnig** [comment]
@mvorisis I am really sorry to tell you that it was made with swift 3 and can only be opoend with xcode 8.0+ now

**Comment by mvorisis** [comment]
Ok I found a previous update of your repo and It worked perfectly.
I also managed to find a mac with xcode 8 and some things returns some errors too

**Comment by jasnig** [comment]
@mvorisis Oh yes ! I just want to tell you that there is an old version may be work . I have not tested it with the latest xcode 8.0(updated by xcode8.0 beta), and so it can meet errors now . Thanks for your reminder.
